### ISSUE TITLE
Wrong sensor ID for battery voltage telemetry

### ISSUE THREAD

**Issue by such-code** [flyduino/kissfc-firmware#12] opened 2020-08-29 15:38 UTC
Setup: TBS Tango 2, Kiss CompactCTRL, TBS Crossfire Nano RX.
Issue: TBS RX reports its voltage using same sensor ID as FC reports battery voltage. Both those sources are discovered in TBS Tango 2 as single RxBt sensor and its value jumps from 4.5V to *Battery voltage*V and back all the time. This makes TX alerts based on telemetry impossible to configure.

**Comment by krunked-fpv** [comment] 2020-08-29 15:57
I noticed this too but only when going to TBS 4.0...  rxbat will blink between 5v and vbat.

**Comment by lichtl** [comment] 2020-09-01 17:46
yes. Same with consumption. Since 4.0. I've raise this with TBS and they confirmed a bug (not sure if fixed in 4.0.2)

**Comment by krunked-fpv** [comment] 2020-09-01 18:47
yes this was fixed in 4.0.2!  thank you

**Closed as completed** 2020-12-16 16:54 UTC
